### ISSUE TITLE
Incorrect rendering of loading/intro image in some games

### ISSUE THREAD

**Issue by polpettedorso** [midwan/amiberry#353]
Some of these games (e.g. Banshee, Hollywood Poker Pro, Bloody Money...) don't display correctely: please take a look at the attached picture.
This happen when installing via code, but it is ok via binary installation

![1528468256097-20180608_162321-resized](https://user-images.githubusercontent.com/43554601/45978423-a4384a00-c04c-11e8-9653-aff9dde21279.jpg)

**Comment by midwan** [comment]
@polpettedorso 
Thanks for the report.

This is related to the latest updates I made in the `dev` version, where I merged in some code from WinUAE. It included blitter and drawing functions, and those I suspect caused this effect.

I'll look into it and fix it.

**Comment by nemo93** [comment]
Hi! I do confirm this behaviour also with Alien Breed2, Dungeon Master 2.

**Comment by midwan** [comment]
@polpettedorso 
Did you test this in the `dev` branch version or the `master` one?

I can't recreate it with the current `dev` which has the latest updates from WinUAE.

**Comment by polpettedorso** [comment]
I just updated form source and the bug is still there...  :-(

**Comment by CypherXG** [comment]
Same bug i had on the iPad. But i never fixed it.
It has to do with the color rendering of the HAM Mode.

**Comment by polpettedorso** [comment]
> Same bug i had on the iPad. But i never fixed it.
> It has to do with the color rendering of the HAM Mode.

Pelare note that in the stable version the bug does not occur

**Comment by midwan** [comment]
@polpettedorso 
OK, so does this happen only on HAM screens? How about HAM screens from Workbench, showing images?
In my version of Banshee, I didn't see the problem - unless there's another version that you tested with (e.g. CD32?)

Maybe I can recreate it with another title then, we'll see.

**Comment by polpettedorso** [comment]
I Think it's only with ham screens. 
I tried also with "links" (the golf game) whose menu are ham and it is all buggy

**Comment by CypherXG** [comment]
I tried many Games like Blood Money or Demos.
It make no difference if they start from WHDLoad or direct from ADF File.
Also it make no difference if you are changing between OCS, ECS or AGA or changing the Chipset.
Best is to find out if you use a Paint Programm like Dpaint which can select a HAM Screenmode.
Here a Screenshot from Stryx:
![screenshot](https://user-images.githubusercontent.com/7895130/46591800-68c26480-cabd-11e8-8f2d-cdf716d0ba8d.png)
Here from Bloodmoney
![screenshot](https://user-images.githubusercontent.com/7895130/46591948-b25f7f00-cabe-11e8-9a7a-58dd8109a3c2.png)
Or from Hollywood Poker Slideshow
Mmhhh in the Slideshow it look like that the Red color is missing or incorrect shown:
![screenshot](https://user-images.githubusercontent.com/7895130/46591822-b5a63b00-cabd-11e8-90e0-b28985d295ae.png)
![screenshot](https://user-images.githubusercontent.com/7895130/46592002-1bdf8d80-cabf-11e8-816a-30dc746f8243.png)
I hope i can help you with this informations...

**Comment by CypherXG** [comment]
> 
> 
> > Same bug i had on the iPad. But i never fixed it.
> > It has to do with the color rendering of the HAM Mode.
> 
> Pelare note that in the stable version the bug does not occur

In the stable Version the GFX Render Code was not changed.
After that the Statusbar was incorrect shown in 16bit RTG mode or in some Amiga Screenmodes. 
The Scanlinebug is there and the wrong color mode.
I think something is wrong with the drawing or amiberrygfx code.
The picasso code seems to be ok, because RTG Render works and the errors are also shown if you don't usw WHD Load mit RTG in the backround.

**Comment by midwan** [comment]
@CypherXG 
Thanks, I think I know what caused this then.
I'll work on fixing it these days and update the `dev` branch accordingly, after testing it.

**Comment by midwan** [comment]
This is now fixed, at least according to the tests I made with the samples mentioned above.
If you find another issue with HAM modes, please let me know.

**Comment by midwan** [comment]
@polpettedorso 
Are you sure you got the `dev` branch?

**Comment by CypherXG** [comment]
Dev branch is fixed. Working perfectly.
You have to replace only your drawing.cpp. That's all.

Nice work. Midwan.

**Comment by polpettedorso** [comment]
Sorry to bother you again: I'm a newbie and not a programmer, but I'd like to contribute at least testing.
Via putty I gave the following instructions:

```
cd ~
git clone -b dev https://github.com/midwan/amiberry.git  
cd amiberry
```

then

`make all
`
I come back to retropie, but there was still the old version of amiberry. Then I tried to update from source, but I think it installed the master version.

I'm sure I'm doing something wrong, but I couldn't figure out what. 
Could you please help me?

thanks

**Comment by polpettedorso** [comment]
Nevermind my request, i found this: https://github.com/midwan/amiberry/wiki/Compiling-Development-Branch and I did it.
Amiberry works great. I will keep on testing the new developments.
Thanks for the great work
