### ISSUE TITLE
Creating HDF >2GB not working

### ISSUE THREAD

**Issue by digitalMedic** [midwan/amiberry#581]
**Describe the bug**
Unable to create a hdf file greater than 2GB.  This behavior occurs before getting into the emulator.  Once in the emulator, the file does not appear.

**To Reproduce**
Create a hdf file and make it greater than 2GB, the file willl be created to a max of 2GB and show that amount in the config file.

**Expected behavior**
Expect to be able to create a hdf file greater than 2GB as it is reported to be supported.

**Screenshots**
![20200130_153243](https://user-images.githubusercontent.com/7312961/73488425-ea0ace00-4376-11ea-8720-e376e01d141d.jpg)
*Creating the 16GB hdf file in Amiberry*

![20200130_153302](https://user-images.githubusercontent.com/7312961/73488477-03137f00-4377-11ea-8744-b3c607a3c431.jpg)
*Notice that the hdf file size is only reported as 2GB despite creating a 16GB file*

![20200130_153435](https://user-images.githubusercontent.com/7312961/73488524-17577c00-4377-11ea-9bc1-895f6a1b7cec.jpg)
*Creating a 16GB hdf file in WinUAE*

![20200130_153502](https://user-images.githubusercontent.com/7312961/73488577-2d653c80-4377-11ea-9c07-8ada35bb5540.jpg)
*Notice that the correct size hdf is created in WinUAE*

**Desktop (please complete the following information):**

- OS: DietPi

- Version 6.28 (Hotfix)

**Comment by solskogen** [comment]
As a workaround (until this gets fixed) you can create a HDF file manually like this:
`truncate -s 6G MyDisk.hdf` and select that file

**Comment by digitalMedic** [comment]
Hello, thanks for the tip.  I tried it and it worked.  One interesting thing about creating a hdf file this way is that it does not show up in HDTools of the 3.1.4 install disk.  How can I change the file system of the created drive?

> As a workaround (until this gets fixed) you can create a HDF file manually like this:
> `truncate -s 6G MyDisk.hdf` and select that file

**Comment by solskogen** [comment]
Yeah, you don't need to partition it when doing it that way. It will show
up in workbench a a NDOS, and you can just format it right away.
If you need RDB you can use amiga-fdisk (available in Raspbian) on the file
before using it in Amiberry.

**Comment by solskogen** [comment]
Even better: use https://github.com/cnvogelg/amitools

amiga-fdisk doesn't seem to work on HDF files bigger than 1G.

**Comment by midwan** [comment]
Please test with the latest commit, it should work from Amiberry as well now. ;)

**Comment by digitalMedic** [comment]
Tried with a new compile (-j2 rpi4) and it is not working correctly.  I created an 8GB hardfile and Amiberry reports it as 0.0M.  At first it appeared as though it may have just reported the size wrong because when I went in to change the interface from UAE to IDE, it reported 8 surfaces, but when I went to start the emulator it crashed.  I have attached the log file.
[amiberry_log.txt](https://github.com/midwan/amiberry/files/4162172/amiberry_log.txt)

**Comment by midwan** [comment]
Thanks, it looks like this needs some more work...

**Comment by midwan** [comment]
it should work now, tested it with a few HDFs > 2GB and they were created normally here.

**Comment by digitalMedic** [comment]
Compiled a version using -j2 PLATFORM=rpi4.  I can create a hdf > 2GB now and it will show up on the WB as DH0:No DOS.  It will not show up in HDTools though.  One other problem that is new in this release, I cannot select the controller to use in the hdf property.  The dropdown box is registering two left mouse clicks.  It is the only box that is doing it consistently.  When I went to configure the location and name of the hdf, it also was double left mouse clicking so it would just jump back to the root Amiberry directory.  I quit Amiberry and restarted it and that stopped.  The controller issue remains though.  The double mouse click isn't happening in Raspbian.

**Comment by midwan** [comment]
@digitalMedic 
the situation should be improved now, I believe :)

**Comment by digitalMedic** [comment]
All seems to be working.  I still do not get the created hard drive file to show up in AmigaOS 3.1.4's HDTools.  It just goes immediately to a NoDos file that can be formatted on the WB.  This works, but it doesn't allow for a custom file system.

**Comment by solskogen** [comment]
As I've said earlier, it's easier to create the file with 'truncate' and
use amitools ( https://github.com/cnvogelg/amitools ) on the file to create
a RDB. Then you can create custom file systems on it.

**Comment by digitalMedic** [comment]
I remember what you said, but I thought that you should not use disk type tools under the new AmigaOS 3.1.4 as they can cause corruption.  Also, it is not how a classic (real) Amiga works.  Many of the online guides to partitioning a hard drive illustrate using HDTools to do this work.  If you don't want to implement this that is fine, but just say so so that I stop bugging you about it and being a pest, which I do not want to be.

**Comment by solskogen** [comment]
I only use amitiools to enable RDB, not to partition or format the drive.
HDF images can either be in RDB format (which requires you to use HDtools)
or as a single partition (which is what happens if you don't make the HDF
file a RDB image).

In WinUAE you can create both single partition hdf *and* as RDB image.
@midwan should comment if he thinks amiberry also need that.

**Comment by midwan** [comment]
@digitalMedic Thanks for confirming.

For now, I think we could close this issue as the original problem has been addressed (being able to create HDFs >2GB).

Further improvements to the functionality can come in the future, but they should not belong to a bug report case like this. :)
