### ISSUE TITLE
Strange gfx + color issue with latest dev

### ISSUE THREAD

**Issue by Gerbinist** [midwan/amiberry#773]
- Raspberry Pi 400
- Raspberry Pi OS
- Linux PI400 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
- DispmanX

Symptoms:
- When starting the latest dev version, my WB boots to a PAL screen, where a UAE gfx screen was configured correctly earlier
- Not all drives (.hdf) are mounted (0, 1 and 2 are OK, 3 is the biggest and is NOK, 4 is a mount point that also works correctly)
- When changing to a UAE gfx screen, the main color turns to blue (where it was red before...). Windows have strange colors too.

I went all the way back to 20-12 where the issue is also seen:

01-02 Issue
14-01 Issue
31-12 Issue
20-12 Issue

Then I made a jump to 06-12 (6519e74), here everything is OK again...

Do you want me to finetune it even more between 06-12 and 20-12 or do you have an idea where this is coming from when looking at the symtoms described above?

**Comment by midwan** [comment]
The 32-bit P96 modes changed pixel format, to sync with WinUAE. This unfortunately means that your existing screenmode will need to be updated, if you were using a 32-bit mode (16-bit ones are unaffected).

There are two steps to do:
1) Open the GUI -> RTG Panel and select the default pixel modes for both 16 and 32-bit options. The default ones are indicated with an asterisk. Save the config afterwards.
2) Boot your Workbench, open Screenmode, select your desired mode. It should now work normally.

I'm not sure what the problem is with your drives, but in any case, if you are upgrading from an older version, I recommend you recreate the config as a troubleshooting step.

**Comment by Gerbinist** [comment]
Thanks midwan, changing the 32-bit variant to the default value and afterwards resaving the WB Screenmode prefs solved the screen and color issues.

One drive still not seen, I'll start working on recreating the config file.

**Comment by Gerbinist** [comment]
Hmm, no...

When starting adding the first Hardfile, all is ok, I see the size of the hardfiles being updated in the settings window while I'm adding each one:

DH0: 40 MB
DH1: 500 MB
DH2: 500 MB
DH3: n/a

DH3: remains n/a when choosing the specific hardfile. Started configuring from scratch (file is around 2 GB). All is still OK in the version from 06-12.

**Comment by Gerbinist** [comment]
midwan,

The only thing that is a bit "out of the ordinary" here is that the hdf that I created with WinUAE is 2046 MB big (although that shouldn't matter), but this way I can use it on the real 1200 as well (slightly smaller than 2 GB).

This has worked before with amiberry though, but perhaps this additional comment triggers something on your end.


Regards

**Comment by midwan** [comment]
What options did you use in WinUAE when you created it?
![image](https://user-images.githubusercontent.com/3877365/109270067-c9c57100-780d-11eb-832b-4b55b541139d.png)

I'd like to recreate that scenario here...

**Comment by Gerbinist** [comment]
All default (like displayed on your screenshot). Just click 'Create' (I used HDF3.hdf as name).

**Comment by Gerbinist** [comment]
It's "hit & miss" when adding Hardfiles. For instance when starting from scratch and I choose HDF0.hdf (40 MB) here, sometimes the configuration panel jumps from n/a to 40 MB. Sometimes it remains on n/a... very strange.

**Comment by Gerbinist** [comment]
Same applies to the RTG settings (the "hit & miss" part). This morning I booted up the Pi, started amiberry and it opened a PAL screen again. Quitting and restarting amiberry took me to a UAE gfx (p96) screen again ('One second reboot pause' active).

**Comment by midwan** [comment]
If I create the HDF in WinUAE, then just transfer it to the Pi, I can use HDToolbox to partition it normally, then format it. It seems to work for me.

GUI screenshot:
![image](https://user-images.githubusercontent.com/3877365/109272571-5887bd00-7811-11eb-9c1f-9c943618e8e7.png)

HDToolbox:
![image](https://user-images.githubusercontent.com/3877365/109272628-6b01f680-7811-11eb-8bca-96629f5c8e71.png)

Workbench, after quick formatting the drive:
![image](https://user-images.githubusercontent.com/3877365/109272662-7c4b0300-7811-11eb-898e-7248af72eddc.png)

I used WB3.9 with BB4 for this test.

**Comment by Gerbinist** [comment]
Current version:

![Current](https://user-images.githubusercontent.com/48334482/109283090-a35c0180-781e-11eb-9a46-4c04cad12397.jpg)

Version from 06-12-2020:

![20201206](https://user-images.githubusercontent.com/48334482/109283135-b078f080-781e-11eb-8547-5aad960d8dda.jpg)

**Comment by Gerbinist** [comment]
Started from scratch and all is good again with the latest dev version. Still strange... must be a consequence of using dev versions ;)
